apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"pose-estimator","namespace":"assignment1"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"pose-estimator"}},"template":{"metadata":{"labels":{"app":"pose-estimator"}},"spec":{"containers":[{"image":"imhero2k/pose-estimation","name":"pose-container","ports":[{"containerPort":5000}],"resources":{"limits":{"cpu":"0.5","memory":"512Mi"},"requests":{"cpu":"0.5","memory":"512Mi"}}}]}}}}
  creationTimestamp: "2025-04-22T01:56:24Z"
  generation: 70
  name: pose-estimator
  namespace: assignment1
  resourceVersion: "386167"
  uid: 04e7ead3-a20d-44e4-8332-f75a66e8026e
spec:
  progressDeadlineSeconds: 600
  replicas: 8
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pose-estimator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pose-estimator
    spec:
      containers:
      - image: imhero2k/pose-estimation
        imagePullPolicy: Always
        name: pose-container
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 8
  conditions:
  - lastTransitionTime: "2025-04-22T01:56:24Z"
    lastUpdateTime: "2025-04-22T01:57:21Z"
    message: ReplicaSet "pose-estimator-b75654f89" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-25T00:15:58Z"
    lastUpdateTime: "2025-04-25T00:15:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 70
  readyReplicas: 8
  replicas: 8
  updatedReplicas: 8